services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27035:27035"  # Usar un puerto diferente para evitar conflictos

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27035/gestioner?authSource=admin
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3015:3000"  # Usar un puerto diferente para evitar conflictos
    restart: always

volumes:
  mongo_data: