version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo_service
    ports:
      - "27050:27017"
    environment:
      - MONGO_INITDB_DATABASE=gestioner
    restart: unless-stopped

  backend:
    build: .
    container_name: backend_service
    ports:
      - "5000:3000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gestioner
    depends_on:
      - mongo
    restart: unless-stopped
